title: Stackbit Personal Theme
baseURL: /
params:
  layout_type: full-width
  style: classic
  palette: blue
  mode: light
  base_font: sans-serif
  header:
    title: Personal Theme
    logo: images/app.webp
    logo_alt: Alyvia logo
    has_primary_nav: true
    primary_nav_links:
      - label: Ayuda
        url: /faq
        style: link
    has_secondary_nav: false
    has_anncmnt: true
    anncmnt_content: "CUIDADO cualquier persona que tenga el hash podrá acceder a tu archivo, no lo compartas con nadie \U0001F64F\U0001F3FD\n"
    anncmnt_align: center
    anncmnt_has_close: true
  footer:
    has_social: false
    social_links: {}
    content: 'cloudhealy, alpha version<br>v0.0.1'
  domain: 'https://example-da691.netlify.app'
  favicon: images/favicon.png
taxonomies:
  stub: stub
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true
