title: Stackbit Personal Theme
baseURL: /
params:
  layout_type: full-width
  style: classic
  palette: red
  mode: light
  base_font: sans-serif
  header:
    title: Personal Theme
    logo: images/app.webp
    logo_alt: Alyvia logo
    has_primary_nav: true
    primary_nav_links:
      - label: Ayuda
        url: /faq
        style: link
    has_secondary_nav: false
    has_anncmnt: true
    anncmnt_content: "CUIDADO cualquier persona que tenga el hash podrá acceder a tu archivo, no lo compartas con nadie \U0001F64F\U0001F3FD\n"
    anncmnt_align: center
    anncmnt_has_close: true
  footer:
    logo: images/logo.svg
    logo_alt: Alyvia logo
    has_primary_nav: true
    primary_nav_links:
      - label: About
        url: /about
        style: link
      - label: FAQ
        url: /faq
        style: link
      - label: Contact me
        url: /contact
        style: link
    has_secondary_nav: true
    secondary_nav_links:
      - label: Style Guide
        url: /style-guide
        style: link
      - label: Terms & Conditions
        url: /terms-conditions
        style: link
      - label: Privacy Policy
        url: /privacy-policy
        style: link
    has_social: true
    social_links:
    content: >-
      cloudhealy, alpha version <br>
      v0.0.1
  domain: 'https://example-da691.netlify.app'
taxonomies:
  stub: stub
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true
